### PR TITLE
fix: correct wording and added citation for 'nostalgic jobs'

### PR DESCRIPTION
**Pull request by 749**

### CODE REVIEW

**Comment by daveshap** [comment]
This is great, thank you. It has a conflict with the other citation that was just added. Can you rectify and update the PR?

**Comment by 749** [comment]
> This is great, thank you. It has a conflict with the other citation that was just added. Can you rectify and update the PR?

Yep just updated it. I removed the numbers from the citations and adopted the style of the other citation. The numbers would make it more difficult for multiple people to add citations.

Good Luck on your experiment, its keeping me on the edge of my seat ;-)

**Comment by Vacyyyy** [comment]
Regarding the numbers, I have noticed that too. However MD doesnt to script tags for a counter without a precompiler. I guess we could use HTML, LaTeX, Typst, or the like, which increases complexity. So we could just leave the reference as `<sup>[citation]</sup>`, which isn't perfect either.

**Comment by 749** [comment]
We could add a script that runs in a GitHub action and updates the numbers on every commit to the david's main.
If that is a desirable solution, I can try and implement it tomorrow.

**Comment by daveshap** [comment]
Don't worry about github actions or even getting it perfect. The final product will be formatted professional in MS word. We just need to get the meat of the content right. Thanks guys!

**Pull request merged**
